const roles = [
  { dates: 'Oct 2024 - Present', title: 'Technical Development Lead (IC)', company: 'Creospan Inc | Northern Trust', location: 'Bengaluru, India', bullets: ['Developed and enhanced Java services for business proceses and  workflow-driven post-trade processing, working with Flowable and BPMN workflows to model, orchestrate and support business processes.', 'Contributed to event-driven microservices using Java and Solace messaging, while improving service observability and tracing with OpenTelemetry.', 'As a self-initiated effort, explored and implemented GenAI solutions using RAG, Text2SQL and LLM orchestration to identify opportunities for more intelligent production support and workflow automation.'] },
  { dates: 'Apr 2024 - Jun 2024', title: 'AI Engineer - GenAI / RAG / Agentic Systems', company: 'Cell Strat AI Lab', location: 'Remote', bullets: ['Designed an end-to-end RAG pipeline for PDF and CSV intelligence using OpenAI and LangChain.', 'Built an agentic Text2SQL framework with chat history, filtering and multi-source querying, plus an OCR pipeline for structured and handwritten documents.', 'Architected AWS Lambda and Chalice services with CDK and Upstash vector search for documents up to 50MB.'] },
  { dates: 'Jun 2022 - Feb 2024', title: 'Senior Java Developer', company: 'Unison Group | DBS Bank Singapore', location: 'ICOM and ADA projects', bullets: ['ICOM: Developed and supported Java-based microservices and API integrations for the omni-channel communication platform, using Kafka for event-driven processing and integrating WhatsApp and LINE channels.', 'ICOM: Worked with Spring Boot, Spring Batch, OAuth2, Solace/Kafka messaging and AWS SNS, SQS and SES while contributing to production-ready deployments and service integrations.', 'ADA: Contributed to the data-lake platform by engineering T1 data ingestion pipelines for real-time transactional data across a multi-tier data-lake architecture.', 'Established Kibana and Grafana dashboards and automated UAT and production deployments through Drone and Jenkins across both project areas.'] },
  { dates: 'Nov 2021 - Mar 2022', title: 'Technical Architect', company: 'Bright Vision | Infosys | ANZ', location: 'IAM and insurance R&D', bullets: ['Worked on OpenTelemetry integration across ForgeRock FRAM, FRIM, IG and DS components.', 'Designed an observability solution using Splunk, New Relic and Dynatrace that became a reusable ANZ standard.', 'Architected an AWS, Docker and Kubernetes Accounts Module for an insurance platform.'] },
  { dates: 'Dec 2020 - Nov 2021', title: 'Principal Software Engineer', company: 'Scoop Technologies | Mavenir Systems', location: 'Telecom', bullets: ['Worked on the monolith-to-microservices migration of the Policy Composer platform, improving scalability by approximately 30%.', 'Worked Open APIs and managed Docker, Kubernetes and CI/CD deployments.'] },
  { dates: 'Sep 2019 - Jan 2020', title: 'Lead Engineer', company: 'Nityo Infotech | ANZ Bank', location: 'Customer Single View', bullets: ['Engineered a Spring Boot microservices and React/TypeScript platform aggregating data across five or more business systems.', 'Designed Open APIs and entitlement-based access control, cutting analyst lookup time by approximately 40%.'] },
  { dates: 'Jun 2018 - Apr 2019', title: 'Staff Software Engineer', company: 'Visa Inc.', location: 'Analytics platform', bullets: ['Migrated an Angular 1.x UI to Angular 6 and automated cross-environment regression testing with Python and Robot Framework.', 'Reduced manual QA effort by approximately 60%.'] },
  { dates: 'Oct 2011 - Apr 2018', title: 'Application Developer -> Senior Developer', company: 'JPMorgan Chase', location: 'Banking and IAM', bullets: ['Delivered React/Redux UI and Spring Boot microservices for the BaNCS banking platform.', 'Managed IAM lifecycle, access management, provisioning and certificates while automating DevOps workflows with Jenkins.'] },
]

export default function App() {
  return <main className="portfolio-page"><div className="container"><div className="page-intro"><p className="eyebrow">Experience</p><h1>A career built around <span>systems that matter.</span></h1><p>18+ years across fintech, banking, telecom and insurance, moving between hands-on engineering, architecture, R&D and technical leadership.</p></div><div className="experience-list">{roles.map((role) => <article className="experience-entry" key={`${role.company}-${role.dates}`}><time>{role.dates}</time><div><h2>{role.title}</h2><h3>{role.company} · {role.location}</h3><ul>{role.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul></div></article>)}</div></div></main>
}
