const projects = [
  { number: '01', title: 'Trade Order Platform', context: 'Lead Developer · Northern Trust / Creospan', description: 'Trade Order Workflows for custody and asset servicing. Contributed as a Lead Developer, Worked on Problems event-driven microservices with Java 8/17 and Solace, improving service reliability, observability and production readiness.', tags: ['Java 8/17', 'Solace', 'Microservices', 'OpenTelemetry', 'REST APIs'] },
  { number: '02', title: 'KB Miner & Cell Bot', context: 'Cell Strat AI Lab', description: 'RAG-based document intelligence and semantic search for PDF and CSV sources. Includes agentic Text2SQL, chat history, OCR processing and serverless APIs for files up to 50MB.', tags: ['OpenAI', 'LangChain', 'AWS Lambda', 'Chalice', 'Upstash'] },
  { number: '03', title: 'Data Lake & Communication Platform', context: 'DBS Bank / Unison Group', description: 'Real-time Kafka ingestion into a multi-tier data lake, paired with an omni-channel API mesh connecting WhatsApp and LINE. AWS messaging services supported production notifications.', tags: ['Kafka', 'AWS SNS', 'SQS', 'SES', 'Spring Batch'] },
  { number: '04', title: 'Customer Single View', context: 'ANZ Bank / Nityo Infotech', description: 'Full-stack data aggregation and entitlement visualization platform unifying five or more business systems, reducing analyst lookup time by approximately 40%.', tags: ['Spring Boot', 'React', 'TypeScript', 'Microservices', 'Open APIs'] },
  { number: '05', title: 'ForgeRock Observability R&D', context: 'ANZ / Bright Vision / Infosys', description: 'Reusable OpenTelemetry framework across ForgeRock components, integrating Splunk, New Relic and Dynatrace and establishing an observability standard across environments.', tags: ['ForgeRock', 'OpenTelemetry', 'Splunk', 'New Relic', 'Dynatrace'] },
  { number: '06', title: 'Policy Composer Modernization', context: 'Mavenir Systems / Scoop Technologies', description: 'Monolith-to-microservices migration and Open API design for a telecom policy management platform, improving scalability by approximately 30%.', tags: ['Microservices', 'Docker', 'Kubernetes', 'CI/CD', 'Open API'] },
]

export default function App() {
  return <main className="portfolio-page"><div className="container"><div className="page-intro"><p className="eyebrow">Selected work</p><h1>Complex problems, <span>made useful.</span></h1><p>Selected systems and R&D initiatives spanning intelligent automation, real-time data, cloud infrastructure and enterprise product design.</p></div><div className="project-showcase">{projects.map((project) => <article className="project-item" key={project.number}><div className="project-number">{project.number}</div><div><p className="eyebrow">{project.context}</p><h2>{project.title}</h2><p>{project.description}</p><div className="tag-list">{project.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div></article>)}</div></div></main>
}
